"""Tests for solo_founder_os.sync — multi-machine git-based sync.

git is mocked via subprocess.run so tests don't actually network.
"""
from __future__ import annotations
import os
import sys

import pytest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

import solo_founder_os.sync as syncmod
from solo_founder_os.sync import (
    DEFAULT_SYNC_IGNORE,
    cmd_init,
    cmd_pull,
    cmd_push,
    cmd_status,
    main,
)


@pytest.fixture(autouse=True)
def _isolate_sync_root(tmp_path, monkeypatch):
    """Redirect SYNC_ROOT into tmp_path so tests don't touch real ~/.solo-founder-os/."""
    monkeypatch.setattr(syncmod, "SYNC_ROOT", tmp_path / ".solo-founder-os")


def _stub_git(monkeypatch, *,
                returncode: int = 0,
                output: str = "",
                track: list | None = None,
                rc_for: dict | None = None):
    """Replace _git with a fake. `rc_for` lets tests vary returncode by
    first arg (the git subcommand)."""
    def fake(*args, cwd=None, capture=True):
        if track is not None:
            track.append(args)
        if rc_for is not None and args and args[0] in rc_for:
            return (rc_for[args[0]], output)
        return (returncode, output)
    monkeypatch.setattr(syncmod, "_git", fake)


def _ns(**kwargs):
    """argparse.Namespace builder for direct cmd_* calls."""
    import argparse
    return argparse.Namespace(**kwargs)


# ──────────────────────────── init ────────────────────────────


def test_init_creates_sync_root_and_gitignore(monkeypatch, tmp_path, capsys):
    _stub_git(monkeypatch)
    rc = cmd_init(_ns(remote="git@github.com:x/y.git", force=False))
    assert rc == 0
    sr = syncmod.SYNC_ROOT
    assert sr.exists()
    gi = sr / ".gitignore"
    assert gi.exists()
    body = gi.read_text()
    # Must include the per-machine state we deliberately exclude.
    assert "usage.jsonl" in body
    assert "cron-logs/" in body
    assert "bandit.sqlite" in body


def test_init_idempotent_skips_when_already_repo(monkeypatch, tmp_path, capsys):
    """Re-running init on an existing repo without --force should refuse."""
    sr = syncmod.SYNC_ROOT
    sr.mkdir(parents=True)
    (sr / ".git").mkdir()  # simulate existing repo
    _stub_git(monkeypatch)
    rc = cmd_init(_ns(remote=None, force=False))
    assert rc == 1
    err = capsys.readouterr().err
    assert "Already a git repo" in err


def test_init_force_rewrites_gitignore(monkeypatch, tmp_path, capsys):
    sr = syncmod.SYNC_ROOT
    sr.mkdir(parents=True)
    (sr / ".git").mkdir()
    (sr / ".gitignore").write_text("# old custom rules\n")
    _stub_git(monkeypatch)
    rc = cmd_init(_ns(remote="git@github.com:x/y.git", force=True))
    assert rc == 0
    body = (sr / ".gitignore").read_text()
    assert "Auto-generated by sfos-sync" in body
    assert "# old custom rules" not in body


def test_init_calls_git_init_when_no_repo(monkeypatch, tmp_path):
    calls: list = []
    _stub_git(monkeypatch, track=calls)
    cmd_init(_ns(remote="git@github.com:x/y.git", force=False))
    # Track args[0] for the subcommand
    cmds = [a[0] for a in calls if a]
    assert "init" in cmds
    assert "remote" in cmds


# ──────────────────────────── status ────────────────────────────


def test_status_errors_when_not_repo(monkeypatch, tmp_path, capsys):
    rc = cmd_status(_ns())
    assert rc == 1
    err = capsys.readouterr().err
    assert "not yet a git repo" in err


def test_status_runs_git_status_when_repo(monkeypatch, tmp_path, capsys):
    sr = syncmod.SYNC_ROOT
    sr.mkdir(parents=True)
    (sr / ".git").mkdir()
    _stub_git(monkeypatch, output="## main...origin/main\n M skills/x.md")
    rc = cmd_status(_ns())
    assert rc == 0
    out = capsys.readouterr().out
    assert "main" in out
    assert "skills/x.md" in out


# ──────────────────────────── push ────────────────────────────


def test_push_errors_when_not_repo(monkeypatch, tmp_path, capsys):
    rc = cmd_push(_ns(message=None))
    assert rc == 1
    err = capsys.readouterr().err
    assert "not a git repo" in err


def test_push_no_changes_still_attempts_push(monkeypatch, tmp_path, capsys):
    """Clean working tree → no commit, but still try push (might be
    behind on previously committed work)."""
    sr = syncmod.SYNC_ROOT
    sr.mkdir(parents=True)
    (sr / ".git").mkdir()
    calls: list = []
    # diff --cached --quiet returns 0 when no staged changes
    _stub_git(monkeypatch, returncode=0, track=calls)
    rc = cmd_push(_ns(message=None))
    assert rc == 0
    cmds = [a[0] for a in calls if a]
    assert "add" in cmds
    assert "diff" in cmds
    assert "push" in cmds  # tries push even with no commit
    assert "commit" not in cmds  # but no commit


def test_push_with_changes_commits_and_pushes(monkeypatch, tmp_path, capsys):
    sr = syncmod.SYNC_ROOT
    sr.mkdir(parents=True)
    (sr / ".git").mkdir()
    calls: list = []
    # diff --cached --quiet returns 1 when there ARE staged changes
    _stub_git(monkeypatch,
                rc_for={"diff": 1},  # changes exist
                track=calls)
    rc = cmd_push(_ns(message="weekly drift report"))
    assert rc == 0
    cmds = [a[0] for a in calls if a]
    assert "commit" in cmds
    # Look for the message in the commit args
    commit_call = next(a for a in calls if a and a[0] == "commit")
    assert "weekly drift report" in commit_call


def test_push_default_commit_message_includes_hostname(monkeypatch, tmp_path):
    sr = syncmod.SYNC_ROOT
    sr.mkdir(parents=True)
    (sr / ".git").mkdir()
    calls: list = []
    _stub_git(monkeypatch, rc_for={"diff": 1}, track=calls)
    cmd_push(_ns(message=None))
    commit_call = next(a for a in calls if a and a[0] == "commit")
    msg = commit_call[2]
    assert "sync:" in msg
    assert os.uname().nodename in msg


# ──────────────────────────── pull ────────────────────────────


def test_pull_errors_when_not_repo(monkeypatch, tmp_path, capsys):
    rc = cmd_pull(_ns())
    assert rc == 1


def test_pull_runs_ff_only(monkeypatch, tmp_path, capsys):
    sr = syncmod.SYNC_ROOT
    sr.mkdir(parents=True)
    (sr / ".git").mkdir()
    calls: list = []
    _stub_git(monkeypatch, output="Already up to date.", track=calls)
    rc = cmd_pull(_ns())
    assert rc == 0
    pull_call = next(a for a in calls if a and a[0] == "pull")
    assert "--ff-only" in pull_call


def test_pull_diverged_emits_recovery_hint(monkeypatch, tmp_path, capsys):
    sr = syncmod.SYNC_ROOT
    sr.mkdir(parents=True)
    (sr / ".git").mkdir()
    _stub_git(monkeypatch, returncode=1,
                output="hint: divergent branches; ! [rejected] non-fast-forward")
    rc = cmd_pull(_ns())
    assert rc == 1
    err = capsys.readouterr().err
    assert "Divergent state" in err
    assert "rebase" in err


# ──────────────────────────── default ignore list ────────────────────────────


def test_default_sync_ignore_excludes_secrets_and_volatility():
    """Privacy + noise guard: the default exclude list MUST include the
    known per-machine / sensitive paths. Regression on this is the
    kind of bug that ships an API key to a private GitHub repo."""
    rules = "\n".join(DEFAULT_SYNC_IGNORE)
    assert "usage.jsonl" in rules
    assert "cron-logs" in rules
    assert "cron/" in rules
    assert "bandit.sqlite" in rules


# ──────────────────────────── CLI dispatcher ────────────────────────────


def test_main_status_dispatches(monkeypatch, tmp_path, capsys):
    rc = main(["status"])
    # Without a repo the cmd_status returns 1; the assertion is just
    # that argparse routes correctly.
    assert rc == 1


def test_main_init_dispatches(monkeypatch, tmp_path):
    _stub_git(monkeypatch)
    rc = main(["init", "git@github.com:x/y.git"])
    assert rc == 0
