"""sfos-cron — install / uninstall / status the weekly self-improvement jobs.

After v0.18.0 closed the L4↔L6 loop, the question was: who actually runs
sfos-eval / sfos-evolver / sfos-retro every week? This module is the
answer. It generates launchd plists + bash wrappers + loads them.

Three jobs, all weekly, staggered so each runs after the previous one
has fresh data to consume:

    Sunday 08:00 — sfos-eval        # judge new examples
    Sunday 09:00 — sfos-evolver     # read fresh evals + reflexion
    Sunday 09:30 — sfos-retro       # weekly cross-agent digest

Each plist points to a tiny bash wrapper at
    ~/.solo-founder-os/cron/run-<job>.sh
that sources ~/.zshrc (where ANTHROPIC_API_KEY lives) and execs the
Python module. Logs go to ~/.solo-founder-os/cron-logs/.

Usage:
    sfos-cron install            # write plists + wrappers + launchctl load
    sfos-cron install --plan     # print what would happen, write nothing
    sfos-cron uninstall          # unload + delete plists (wrappers stay)
    sfos-cron status             # which jobs are loaded?

Why launchd not crontab: macOS deprecated cron in favor of launchd.
launchd survives reboot, integrates with `launchctl list`, and the
plist format is what every other agent in this stack uses.

Linux fallback: this CLI emits a `crontab` block on `--linux` for
copy-paste install on non-darwin hosts.
"""
from __future__ import annotations
import argparse
import pathlib
import platform
import subprocess
import sys
from dataclasses import dataclass
from typing import Optional

from .scheduler import build_cron_line, build_launchd_plist, launch_agent_path


# Where wrapper scripts live. Separate from queue/governance dirs so the
# install surface is one well-known place.
CRON_DIR = pathlib.Path.home() / ".solo-founder-os" / "cron"
LOG_DIR = pathlib.Path.home() / ".solo-founder-os" / "cron-logs"


@dataclass(frozen=True)
class CronJob:
    label: str
    module: str            # python -m <module>
    weekday: int           # launchd: 0 = Sunday
    hour: int
    minute: int
    description: str
    extra_args: tuple[str, ...] = ()


JOBS: list[CronJob] = [
    CronJob(
        label="com.alexji.sfos.eval",
        module="solo_founder_os.eval",
        weekday=0, hour=8, minute=0,
        description="L6 — judge recent record_example rows with Sonnet, "
                    "persist mean/p10/p50 per skill.",
    ),
    CronJob(
        label="com.alexji.sfos.council",
        module="solo_founder_os.council",
        weekday=0, hour=8, minute=30,
        description="L5 — convene a BUG_TRIAGE council per skill whose "
                    "mean dropped > 0.7 in last week's eval (severe drift "
                    "only; routine drift goes straight to L4).",
        extra_args=("--auto-from-drift",),
    ),
    CronJob(
        label="com.alexji.sfos.evolver",
        module="solo_founder_os.evolver",
        weekday=0, hour=9, minute=0,
        description="L4 — scan reflexion FAILED rows + L6 drift signals; "
                    "Haiku synthesizes PR-gated proposals.",
    ),
    CronJob(
        label="com.alexji.sfos.retro",
        module="solo_founder_os.cross_agent_report",
        weekday=0, hour=9, minute=30,
        description="Cross-agent weekly retro digest "
                    "(reflection / skill / preference / bandit).",
    ),
]


# ───────────────── wrapper script ─────────────────


def _wrapper_path(job: CronJob) -> pathlib.Path:
    return CRON_DIR / f"run-{job.label.split('.')[-1]}.sh"


def _log_path(job: CronJob, *, stream: str) -> pathlib.Path:
    return LOG_DIR / f"{job.label}.{stream}.log"


def _python_executable() -> str:
    """Use the current interpreter so the wrapper can import installed
    packages exactly like a developer running it by hand. Falls back to
    /usr/bin/env python3 if sys.executable looks odd (e.g. embedded)."""
    exe = sys.executable
    if exe and pathlib.Path(exe).exists():
        return exe
    return "/usr/bin/env python3"


def render_wrapper(job: CronJob) -> str:
    """Render the bash wrapper that launchd will exec.

    Sources ~/.zshrc to pick up ANTHROPIC_API_KEY (Alex's convention).
    Sources ~/.zshenv first because it's strictly more conservative and
    runs in non-interactive shells without barfing.
    """
    py = _python_executable()
    args_str = " ".join(f'"{a}"' for a in job.extra_args)
    body = [
        "#!/usr/bin/env bash",
        f"# {job.description}",
        "# Auto-generated by sfos-cron — DO NOT EDIT BY HAND.",
        "set -u",
        "",
        # CWD discipline: launchd inherits whatever CWD the plist was
        # loaded from. If that's a Python project dir, sys.path picks
        # up its `solo_founder_os/` subdir which can shadow the
        # pip-installed package and cause partial-import failures
        # ('No module named .source'). cd to $HOME — neutral,
        # always exists, never has a stray Python package.
        'cd "$HOME"',
        "",
        "# Pick up ANTHROPIC_API_KEY etc. ~/.zshenv runs unconditionally,",
        "# ~/.zshrc may guard on $- so guard locally.",
        '[ -f "$HOME/.zshenv" ] && . "$HOME/.zshenv"',
        '[ -f "$HOME/.zshrc" ] && . "$HOME/.zshrc"',
        "",
        f'mkdir -p "{LOG_DIR}"',
        # `-W ignore::RuntimeWarning:runpy` suppresses the cosmetic
        # warning Python emits when a `python -m foo.bar` invocation
        # finds `foo.bar` already imported via foo.__init__.py. The
        # filter is scoped to the runpy module so legitimate runtime
        # warnings from agent code still surface in cron-logs/*.err.log.
        f'exec "{py}" -W ignore::RuntimeWarning:runpy '
        f'-m {job.module} {args_str}'.rstrip(),
        "",
    ]
    return "\n".join(body)


# ───────────────── install / uninstall ─────────────────


def _ensure_dirs() -> None:
    CRON_DIR.mkdir(parents=True, exist_ok=True)
    LOG_DIR.mkdir(parents=True, exist_ok=True)


def write_job_files(job: CronJob) -> tuple[pathlib.Path, pathlib.Path]:
    """Write plist + wrapper for one job. Returns (plist_path, wrapper_path).
    Idempotent: re-running just overwrites the files.
    """
    _ensure_dirs()
    wrapper = _wrapper_path(job)
    wrapper.write_text(render_wrapper(job), encoding="utf-8")
    wrapper.chmod(0o755)

    plist_text = build_launchd_plist(
        label=job.label,
        program=["/bin/bash", str(wrapper)],
        schedule={
            "weekday": job.weekday,
            "hour": job.hour,
            "minute": job.minute,
        },
        stdout_path=str(_log_path(job, stream="out")),
        stderr_path=str(_log_path(job, stream="err")),
    )
    plist_path = launch_agent_path(job.label)
    plist_path.parent.mkdir(parents=True, exist_ok=True)
    plist_path.write_text(plist_text, encoding="utf-8")
    return plist_path, wrapper


def _launchctl(*args: str) -> tuple[int, str]:
    """Run `launchctl args...` and capture stdout+stderr. Returns
    (returncode, combined_output). Never raises on non-zero exit; the
    install path needs to surface errors to the user, not crash."""
    try:
        r = subprocess.run(
            ["launchctl", *args],
            capture_output=True, text=True, timeout=10,
        )
    except FileNotFoundError:
        return (127, "launchctl not on PATH (not running on macOS?)")
    except subprocess.TimeoutExpired:
        return (124, "launchctl timed out after 10s")
    return (r.returncode, (r.stdout + r.stderr).strip())


def install_one(job: CronJob, *, load: bool = True) -> dict:
    """Write files, optionally launchctl load. Returns a status dict
    suitable for printing."""
    plist, wrapper = write_job_files(job)
    info: dict = {
        "label": job.label,
        "plist": str(plist),
        "wrapper": str(wrapper),
        "loaded": False,
    }
    if not load:
        return info
    # Reload-style sequence: try unload first (idempotent across runs),
    # then load -w to mark it persistent.
    _launchctl("unload", str(plist))
    rc, out = _launchctl("load", "-w", str(plist))
    info["loaded"] = (rc == 0)
    if rc != 0:
        info["load_error"] = out
    return info


def uninstall_one(job: CronJob) -> dict:
    """Unload + delete plist. Wrapper script stays so logs remain
    interpretable post-uninstall."""
    plist = launch_agent_path(job.label)
    info = {"label": job.label, "plist": str(plist), "removed": False}
    if plist.exists():
        _launchctl("unload", str(plist))
        plist.unlink()
        info["removed"] = True
    return info


def is_loaded(job: CronJob) -> bool:
    """True iff `launchctl list <label>` reports the job exists."""
    rc, _ = _launchctl("list", job.label)
    return rc == 0


def _preflight_sterile_import() -> tuple[bool, str]:
    """Return (ok, hint).

    Runs `python -c "import solo_founder_os"` from cwd=/ — exactly the
    sterile import test that exposed the v0.26.2 launchd cron bug. If
    the package can't import from a neutral CWD, the cron jobs we're
    about to write will fail every Sunday.

    Returns (True, "") on success; (False, install hint) on failure.
    """
    try:
        r = subprocess.run(
            [sys.executable, "-c",
             "import solo_founder_os; print(solo_founder_os.__version__)"],
            cwd="/",
            capture_output=True, text=True, timeout=10,
        )
    except Exception as e:
        return False, f"sub-import crashed: {e}"
    if r.returncode == 0:
        return True, ""
    err_tail = (r.stderr or r.stdout or "").strip().splitlines()[-3:]
    hint = (
        "  solo_founder_os is NOT pip-installed. The launchd cron jobs\n"
        "  would fail every Sunday with ModuleNotFoundError.\n"
        "\n"
        "  Fix from the repo root:\n"
        "      pip install --user -e .\n"
        "\n"
        "  (sterile-import error tail:\n  "
        + "\n  ".join(err_tail) + ")"
    )
    return False, hint


# ───────────────── CLI ─────────────────


def _print_plan(jobs: list[CronJob]) -> None:
    print("Plan:")
    for j in jobs:
        print(f"  • {j.label}")
        print(f"      Sun {j.hour:02d}:{j.minute:02d}  "
              f"python -m {j.module}")
        print(f"      plist:   {launch_agent_path(j.label)}")
        print(f"      wrapper: {_wrapper_path(j)}")
        print(f"      logs:    {_log_path(j, stream='out')}")


def _emit_crontab_block(jobs: list[CronJob]) -> str:
    """For Linux hosts: emit a copy-pasteable crontab block."""
    lines = [
        "# solo-founder-os weekly self-improvement (Linux fallback)",
        "# Install: crontab -l | { cat; echo \"$(below)\"; } | crontab -",
        "",
    ]
    for j in jobs:
        py = _python_executable()
        # cron weekday: 0 = Sunday (same as launchd); minute hour day month dow
        sched = f"{j.minute} {j.hour} * * {j.weekday}"
        cmd = (f'{py} -m {j.module} '
               f'>> {_log_path(j, stream="out")} 2>&1')
        lines.append(build_cron_line(
            schedule=sched, command=cmd, comment=j.description,
        ))
    return "\n".join(lines)


def main(argv: Optional[list[str]] = None) -> int:
    p = argparse.ArgumentParser(
        prog="sfos-cron",
        description="Install / uninstall the SFOS weekly self-improvement "
                     "jobs (sfos-eval / sfos-evolver / sfos-retro).",
    )
    sub = p.add_subparsers(dest="cmd", required=True)

    p_install = sub.add_parser("install",
                                help="Write plists + wrappers, launchctl load")
    p_install.add_argument("--plan", action="store_true",
                            help="Print the plan; write nothing.")
    p_install.add_argument("--no-load", action="store_true",
                            help="Write plists but skip `launchctl load`.")
    p_install.add_argument("--linux", action="store_true",
                            help="Emit a crontab block instead "
                                 "(use on non-darwin).")
    p_install.add_argument("--skip-preflight", action="store_true",
                            help="Skip the sterile-import check (useful "
                                 "for testing the install path itself).")
    sub.add_parser("uninstall",
                    help="Unload + remove all SFOS launchd plists.")
    sub.add_parser("status",
                    help="Show which SFOS jobs are currently loaded.")

    args = p.parse_args(argv)

    if args.cmd == "install":
        if args.linux or platform.system() != "Darwin":
            print(_emit_crontab_block(JOBS))
            return 0
        if args.plan:
            _print_plan(JOBS)
            return 0

        # Pre-flight: refuse to install if solo-founder-os isn't
        # sterile-importable. Otherwise the plists land but every
        # Sunday wake-up fires a ModuleNotFoundError into the void
        # — which is exactly the v0.26.2 production bug we just fixed.
        if not args.skip_preflight:
            ok, hint = _preflight_sterile_import()
            if not ok:
                print("✗ pre-flight FAILED — refusing to install plists.\n",
                      file=sys.stderr)
                print(hint, file=sys.stderr)
                print("\nRe-run with --skip-preflight to install anyway "
                      "(plists will be present but cron will fail).",
                      file=sys.stderr)
                return 2

        load = not args.no_load
        for job in JOBS:
            info = install_one(job, load=load)
            tag = "✓ loaded" if info["loaded"] else (
                "(written, not loaded)" if not load else
                f"⚠️  load failed: {info.get('load_error', '?')}")
            print(f"  {tag}  {info['label']}")
        print(f"\nLogs will appear in {LOG_DIR}/")
        print("First run: next Sunday "
              f"{JOBS[0].hour:02d}:{JOBS[0].minute:02d}.")
        return 0

    if args.cmd == "uninstall":
        for job in JOBS:
            info = uninstall_one(job)
            tag = "✓ removed" if info["removed"] else "(not installed)"
            print(f"  {tag}  {info['label']}")
        return 0

    if args.cmd == "status":
        for job in JOBS:
            tag = "✓ loaded" if is_loaded(job) else "  not loaded"
            plist = launch_agent_path(job.label)
            on_disk = "plist on disk" if plist.exists() else "no plist"
            print(f"  {tag}  {job.label}  ({on_disk})")
        return 0

    return 1


if __name__ == "__main__":
    sys.exit(main())
