"""sfos-sync — multi-machine sync of the SFOS shared state via git.

Alex's brain says "switches machines" → state lives in ~/.dotdirs and
each machine drifts. This wraps git around `~/.solo-founder-os/` so
the cross-agent layer (skills / evals / evolver-proposals / council-
meetings / preference-pairs / retro digests) follows the operator
across machines without each agent's per-machine state polluting it.

What syncs (the SFOS-shared layer — semantically machine-independent):
  ~/.solo-founder-os/skills/                 # Voyager-promoted skills
  ~/.solo-founder-os/evals/                  # Sonnet-judge reports
  ~/.solo-founder-os/evolver-proposals/      # Haiku PR proposals
  ~/.solo-founder-os/council-meetings/       # L5 deliberations
  ~/.solo-founder-os/examples/               # record_example exemplars
  ~/.solo-founder-os/retro-*.md              # weekly digests
  ~/.solo-founder-os/bus/                    # cross-terminal broadcasts
  ~/.solo-founder-os/governance/decisions.jsonl # HITL audit log

What does NOT sync (default .sync-ignore):
  ~/.solo-founder-os/usage.jsonl             # local cost log
  ~/.solo-founder-os/cron-logs/              # machine-specific stdout
  ~/.solo-founder-os/cron/                   # generated wrapper scripts
  ~/.solo-founder-os/bandit.sqlite           # bandit state (per-machine
                                               for now; future v3 may
                                               sync if multi-machine
                                               bandit warmup matters)

Per-agent dirs (~/.<agent>/) are NEVER touched — they have machine-
specific tokens, queue paths, reflexion logs that are just diaries.

CLI:
    sfos-sync init <git-remote-url>  # one-time per machine
    sfos-sync status                  # what's local-only / behind
    sfos-sync push                    # commit + push
    sfos-sync pull                    # git pull
    sfos-sync push --message "..."    # custom commit msg

Why git over Dropbox/iCloud:
- Conflicts surface as merge conflicts, not silent overwrites
- Audit trail: every change is signed by which machine made it
- Private repos on GitHub are free; iCloud Drive sync between two
  Macs has known weird-state failures
- `sfos-sync log` is just `git log`; familiar tooling

Privacy: the user's existing GitHub account works. Repo should be
PRIVATE. The .sync-ignore list above keeps API keys / tokens / cost
logs out by default. Audit it before first push.
"""
from __future__ import annotations
import argparse
import os
import pathlib
import subprocess
import sys
from datetime import datetime, timezone
from typing import Optional


SYNC_ROOT = pathlib.Path.home() / ".solo-founder-os"

# Files / dirs that must NOT be synced — written into .gitignore on init.
DEFAULT_SYNC_IGNORE: list[str] = [
    "# Auto-generated by sfos-sync init — DO NOT remove without thought.",
    "# Per-machine state that drifts and would cause noisy merges:",
    "usage.jsonl",
    "cron-logs/",
    "cron/",
    "bandit.sqlite",
    # Stale evolver / eval reports from before the loop was clean
    "*.test-polluted-*",
    "examples.test-polluted-*/",
]


def _git(*args: str, cwd: Optional[pathlib.Path] = None,
          capture: bool = True) -> tuple[int, str]:
    """Run `git args...` inside `cwd` (default SYNC_ROOT). Returns
    (returncode, combined stdout/stderr). Never raises."""
    try:
        r = subprocess.run(
            ["git", *args],
            cwd=str(cwd or SYNC_ROOT),
            capture_output=capture,
            text=True,
            timeout=60,
        )
    except FileNotFoundError:
        return (127, "git not on PATH")
    except subprocess.TimeoutExpired:
        return (124, "git command timed out after 60s")
    out = (r.stdout or "") + (r.stderr or "")
    return (r.returncode, out.strip())


def _is_git_repo(path: pathlib.Path) -> bool:
    return (path / ".git").exists()


# ──────────────────────────── init ────────────────────────────


def cmd_init(args: argparse.Namespace) -> int:
    """Bootstrap ~/.solo-founder-os/ as a git repo + push to remote."""
    if not SYNC_ROOT.exists():
        SYNC_ROOT.mkdir(parents=True, exist_ok=True)

    if _is_git_repo(SYNC_ROOT):
        print(f"Already a git repo at {SYNC_ROOT}.", file=sys.stderr)
        if not args.force:
            print("Pass --force to re-init (will not delete .git).",
                   file=sys.stderr)
            return 1

    # Write .gitignore (idempotent — overwrites on --force, otherwise
    # only writes if absent).
    gitignore = SYNC_ROOT / ".gitignore"
    if not gitignore.exists() or args.force:
        gitignore.write_text("\n".join(DEFAULT_SYNC_IGNORE) + "\n",
                              encoding="utf-8")
        print(f"  wrote {gitignore}")

    if not _is_git_repo(SYNC_ROOT):
        rc, out = _git("init", "-b", "main")
        if rc != 0:
            print(f"git init failed: {out}", file=sys.stderr)
            return rc
        print("  git init ✓")

    if args.remote:
        # Set / update origin
        _git("remote", "remove", "origin")  # idempotent — ignore failure
        rc, out = _git("remote", "add", "origin", args.remote)
        if rc != 0:
            print(f"git remote add failed: {out}", file=sys.stderr)
            return rc
        print(f"  remote → {args.remote}")

    print("\nReady. Next:")
    print("  sfos-sync push   # commit current state + push to origin")
    print("  sfos-sync pull   # on the OTHER machine, after first push")
    return 0


# ──────────────────────────── status ────────────────────────────


def cmd_status(args: argparse.Namespace) -> int:
    if not _is_git_repo(SYNC_ROOT):
        print(f"{SYNC_ROOT} is not yet a git repo.", file=sys.stderr)
        print("Run: sfos-sync init <git-remote-url>", file=sys.stderr)
        return 1

    rc, out = _git("status", "--short", "--branch")
    if rc != 0:
        print(f"git status failed: {out}", file=sys.stderr)
        return rc
    print(out or "(clean working tree)")
    return 0


# ──────────────────────────── push / pull ────────────────────────────


def cmd_push(args: argparse.Namespace) -> int:
    if not _is_git_repo(SYNC_ROOT):
        print(f"{SYNC_ROOT} is not a git repo. Run sfos-sync init first.",
               file=sys.stderr)
        return 1

    rc, _ = _git("add", "-A")
    if rc != 0:
        return rc

    # Has anything changed?
    rc_diff, _ = _git("diff", "--cached", "--quiet")
    if rc_diff == 0:
        print("Nothing to commit — already up to date.")
        # Still try to push (in case we're behind on local commits)
        rc, out = _git("push", "origin", "main")
        if rc == 0:
            print("Push successful.")
        return rc

    # Compose a meaningful default commit message.
    host = os.uname().nodename
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    msg = args.message or f"sync: {host} → {ts}"
    rc, out = _git("commit", "-m", msg)
    if rc != 0:
        print(f"git commit failed: {out}", file=sys.stderr)
        return rc
    print(f"  committed: {msg}")

    rc, out = _git("push", "origin", "main")
    if rc != 0:
        print(f"git push failed: {out}", file=sys.stderr)
        print("\nFirst push? Try: sfos-sync push --upstream",
               file=sys.stderr)
        return rc
    print("  pushed to origin/main ✓")
    return 0


def cmd_pull(args: argparse.Namespace) -> int:
    if not _is_git_repo(SYNC_ROOT):
        print(f"{SYNC_ROOT} is not a git repo. Run sfos-sync init first.",
               file=sys.stderr)
        return 1
    rc, out = _git("pull", "--ff-only", "origin", "main")
    if rc != 0:
        print(f"git pull failed: {out}", file=sys.stderr)
        if "non-fast-forward" in out or "diverged" in out:
            print(
                "\nDivergent state detected (this machine and remote both "
                "have unique commits). Resolve manually with:\n"
                "  cd ~/.solo-founder-os && git pull --rebase origin main",
                file=sys.stderr,
            )
        return rc
    print(out or "Already up to date.")
    return 0


# ──────────────────────────── CLI entry ────────────────────────────


def main(argv: Optional[list[str]] = None) -> int:
    p = argparse.ArgumentParser(
        prog="sfos-sync",
        description="Multi-machine sync of the SFOS shared state via git.",
    )
    sub = p.add_subparsers(dest="cmd", required=True)

    p_init = sub.add_parser(
        "init",
        help="Bootstrap ~/.solo-founder-os/ as a git repo.",
    )
    p_init.add_argument("remote", nargs="?",
                          help="Git remote URL (e.g. "
                               "git@github.com:you/sfos-state.git). "
                               "Optional on re-init.")
    p_init.add_argument("--force", action="store_true",
                          help="Re-init even if .git already exists "
                               "(rewrites .gitignore).")
    p_init.set_defaults(func=cmd_init)

    p_status = sub.add_parser("status",
                                help="Show what's local-only or out of sync.")
    p_status.set_defaults(func=cmd_status)

    p_push = sub.add_parser("push",
                              help="Commit local changes + push to origin.")
    p_push.add_argument("--message", "-m", default=None,
                          help="Commit message (default: "
                               "'sync: <hostname> → <UTC ts>').")
    p_push.set_defaults(func=cmd_push)

    p_pull = sub.add_parser("pull",
                              help="Pull from origin (fast-forward only).")
    p_pull.set_defaults(func=cmd_pull)

    args = p.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
